var p1 = "Over the past few decades, it has often been said that we no longer have an addressee for our political demands. But that’s not true. We have each other. What we can no longer get from the state, the party, the union, the boss, we ask for from one another. And we provide. Lacan famously defined love as giving something you don’t have to someone who doesn’t want it.1 But love is more than a YouTube link or a URL. This beautiful negative flip of what is commonly considered the most positive force in the universe helps us begin to see love’s fullness and endless bounty, as based in emptiness and lack—in mutual loss. Love’s joy is not to be found in fulfillment, but in recognition: even though I can never return what was taken away from you, I may be the only person alive who knows what it is. I don’t have what it is you’re missing, but knowing its shape already makes a world where you can live without it.";
var p2 = "Now it becomes easy to see how love translates to economic terms as a union based in mutual debt. When the debt is paid off or called in, the union dissolves. And now that pretty much everyone is in debt, love abounds! Professionals are moving back in with their parents, people are returning home to their countries to depend on their extended families, contracts are increasingly backed by personal relationships, and even the values of goods and currencies are backed less by bonds and legal tender and more by the trust and intimacy that gives them their character. Shared associations and affinities expressed over communication lines produce pockets of enormous value in an otherwise lonely ocean of random data streams. Musicians record reams of songs without ever thinking about wanting a record contract from major labels that are still struggling to understand how to make money off computer files.";
var p3 = "Musicians produce music for pure communication now. Information and communication turns immaterial economy into superstition and affective projections. Capital defers down to pure communication, and what used to be an idea of the collective has become a force of conviviality in the absolute. Information-driven overstimulation and actual impoverishment may have fallen in love with each other as well, and they shack up together on an unemployed person’s Facebook page. Now that we live a constant slump, what used to be called biopolitics has been accelerated to the degree that it starts to line up with older pre-capitalist and pre-mercantile means of stabilizing exchanges. Why, after all, do you think there is so much talk about feudalism these days? And how did you suddenly get so many friends that you don’t even like? Where do you think we got all the bromance films—Hollywood romantic comedies on Platonic love between immature men with nothing in common who are nonetheless forced to improve difficult circumstances by forming bonds of intimacy and solidarity? Neighborhood currencies appear, not only in places like Greece, to keep goods and services moving when the money system breaks down. The currency could be a stone or a handshake—it doesn’t matter and doesn’t even have to be material when it’s backed by bonds of trust, by family love, or by friendship. All that is capital melts into love.";
var p4 = "Love is the most recently introduced member in the family of inflation and bloat. It is a burst of fresh air fed straight into the bubble. It gives the Ponzi scheme at least another decade before people start to think about cashing out. Remember when you would run out of time and replace that with energy? Push a little harder and move a little faster and you can trick time, because darling you’re a superhero. But when you run out of time and energy alike, you run into a problem. You need help. You need support. You need love and a bit of tenderness. Now, with the help of others, you can feed the machine again.";
var p5 = "Without time and energy of your own, love is the conduit through which you extract the time and energy of others. You then start to take the shape of that loving conduit. But you have also become a professional lover—or a diabolically good flirt. You are a kind of Marilyn Monroe or Don Juan in the labor of other Marilyns and Dons. This arrangement actually makes for a beautifully collective endeavor so long as you can stay beautiful, tender, and kind to your lovers, and so long as they stay that way to you. This tenderness is a force of resynchronization. Maybe it is a new kind of force altogether. Maybe it is love time. Let’s inhale and exhale together.";
var p6 = "Love is in this sense not an elevated romantic phenomenon but the economization of empathy. Love is immaterial capital in the absolute in a sphere of value relations where capital and labor are no longer the main operators or arbiters of value. As unfixed capital summons higher and higher symbolic registers into the arena of exchange, its increasing abstraction puts it constantly on the prowl for a lower base to peg value to. But we now find ourselves in a moment where the situation has taken hold to the point where we are no longer really talking about value in an economic sense, but rather about how to sustain meaning in its most fundamental semantic and ontological sense. And this meaning is provided by the base-level foundations for life and for identification, for solidarity or for support, in reproductive and affective relations, from childbirth to friendship.";
var p7 = "There is also an idea that solidarities between people within the sphere of capital are capable of compensating for the inequities produced by capital, and that this constitutes a kind of exception to the economy within it. But in fact these solidarities are the very essence of what regulates the flows of value and compensate for its inconsistencies through promises, favors—the handshake or the handjob. Kisses and compliments cost nothing and mean everything, like the phrase “sweet nothings” to describe lovers’ whispers to each other. It is not through the “nothing” but the “sweet” that semiotics becomes material when plucking the strings of the heart. Love abounds on information networks—like a home, every inbox is a cacophony of emotions, of simple pleasures, seething frustrations, of unconditional support and permanent disavowals, of silent treatments and gushing confessions. It is through bonds of solidarity that all the things that that cannot be registered and accounted for—because they are irrational and errant and ill defined suspended interactions—find their place, either due to tolerance or an ability to codify or both. In this sense, what I am talking about is a bloat in the sphere of mutual solidarities, a bubble that is no longer economic but will only burst as an aneurism or an uprising—its effects will not be registered according to any language so far understood as being within the realm of economy. Even if Marx did give us a premonition in his closing lines of “The Power of Money”:";

module.exports = {
  p1: p1,
  p2: p2,
  p3: p3,
  p4: p4,
  p5: p5,
  p6: p6,
  p7: p7,
};
